/*
WITH RECURSIVE 
- 메모리 상에 가상의 테이블 저장
- 가상 테이블 생성

WITH RECURSIVE 테이블명 AS 
(
SELECT 초기값 AS 별칭 
UNION ALL
SELECT 별칭 계산식 
FROM 테이블명
WHERE 조건문
)
*/

-- 0시부터 23시까지 각 시간대별 발생한 입양 건수, 시간 순으로 정렬
WITH RECURSIVE TIMETABLE(HOUR) AS (
    SELECT 0
    UNION
    SELECT TIMETABLE.HOUR + 1 
    FROM TIMETABLE 
    WHERE TIMETABLE.HOUR < 23
)

SELECT HOUR, COUNT(O.ANIMAL_ID)
FROM TIMETABLE AS T 
LEFT JOIN ANIMAL_OUTS AS O 
ON T.HOUR = HOUR(O.DATETIME)
GROUP BY HOUR
ORDER BY HOUR;