-- 20210118 --
-- 1번
SELECT DEPARTMENT_NAME AS 학과명, CATEGORY AS 계열
FROM TB_DEPARTMENT ;

-- 2번
SELECT DEPARTMENT_NAME||'의 정원은'||CAPACITY||'명 입니다' AS "학과별 정원"
FROM TB_DEPARTMENT; 

-- 3번
SELECT DEPARTMENT_NO
FROM TB_DEPARTMENT
WHERE DEPARTMENT_NAME = '국어국문학과' ;

SELECT STUDENT_NAME
FROM TB_STUDENT
WHERE DEPARTMENT_NO = '001'
      AND STUDENT_SSN LIKE '_______2%'
      AND ABSENCE_YN = 'Y' ; 

-- 4번
SELECT STUDENT_NAME
FROM TB_STUDENT
WHERE STUDENT_NO IN ('A513079', 'A513090', 'A513091', 'A513110', 'A513119') ;

-- 5번
SELECT DEPARTMENT_NAME, CATEGORY
FROM TB_DEPARTMENT
WHERE CAPACITY BETWEEN 20 AND 30 ;

-- 6번
SELECT PROFESSOR_NAME
FROM TB_PROFESSOR
WHERE DEPARTMENT_NO IS NULL ;

-- 7번
SELECT STUDENT_NAME
FROM TB_STUDENT
WHERE DEPARTMENT_NO IS NULL ;

-- 8번
SELECT CLASS_NO
FROM TB_CLASS
WHERE PREATTENDING_CLASS_NO IS NOT NULL ; 

-- 9번
SELECT DISTINCT CATEGORY
FROM TB_DEPARTMENT ;

-- 10번
SELECT STUDENT_NO, STUDENT_NAME, STUDENT_SSN
FROM TB_STUDENT
WHERE STUDENT_NO LIKE 'A2%' AND STUDENT_ADDRESS LIKE '%전주%' AND ABSENCE_YN = 'N'
-- WHERE ENTRANCE_DATE LIKE '02%'

-- 20210119 --
-- 1번 
SELECT STUDENT_NO AS 학번,
       STUDENT_NAME AS 이름,
       TO_CHAR(ENTRANCE_DATE,'YYYY-MM-DD') AS 입학년도
FROM TB_STUDENT
WHERE DEPARTMENT_NO = '002'
ORDER BY 3 ;

-- 2번
SELECT PROFESSOR_NAME,
       PROFESSOR_SSN
FROM TB_PROFESSOR
WHERE LENGTH(PROFESSOR_NAME) != 3;

-- 3번 
SELECT PROFESSOR_NAME AS 교수이름,
       TO_CHAR(SYSDATE,'YYYY')
       - TO_CHAR(TO_DATE(SUBSTR(PROFESSOR_SSN,1,6),'RRMMDD'),'YYYY') AS 나이
FROM TB_PROFESSOR 
WHERE TO_CHAR(TO_DATE(SUBSTR(PROFESSOR_SSN,1,6),'RRMMDD'),'YYYY')
      < 2000
ORDER BY 2;

-- 4번
SELECT SUBSTR(PROFESSOR_NAME,2) AS 이름
FROM TB_PROFESSOR;

-- 5번
SELECT STUDENT_NO,
       STUDENT_NAME
FROM TB_STUDENT ;

-- 6번
SELECT TO_CHAR(TO_DATE('20211225','YYYYMMDD'),'DAY') 
FROM DUAL ;

-- 7번
SELECT TO_CHAR(TO_DATE('99/10/11','YY/MM/DD'), 'YYYY"년"MM"월"DD"일"')
FROM DUAL;
SELECT TO_CHAR(TO_DATE('49/10/11','YY/MM/DD'), 'YYYY"년"MM"월"DD"일"')
FROM DUAL;
SELECT TO_CHAR(TO_DATE('99/10/11','RR/MM/DD'), 'YYYY"년"MM"월"DD"일"')
FROM DUAL;
-- 현재 년도가 49 이하고, 지정한 년도가 49 이하이기 때문에 2049 출력
SELECT TO_CHAR(TO_DATE('49/10/11','RR/MM/DD'), 'RRRR"년"MM"월"DD"일"')
FROM DUAL;

-- 8번 
SELECT STUDENT_NO,
       STUDENT_NAME
FROM TB_STUDENT 
WHERE STUDENT_NO LIKE '9%'

-- 9번
SELECT ROUND(AVG(POINT),1) AS 평점
FROM TB_GRADE
WHERE STUDENT_NO = 'A517178' ;

-- 10번
SELECT DEPARTMENT_NO AS 학과번호,
       COUNT(DEPARTMENT_NO) AS "학생수(명)"
FROM TB_STUDENT
GROUP BY DEPARTMENT_NO
ORDER BY DEPARTMENT_NO;

-- 11번
SELECT COUNT(*)
FROM TB_STUDENT
WHERE COACH_PROFESSOR_NO IS NULL ;

-- 12번
SELECT STUDENT_NO,
       TERM_NO,
       POINT
FROM TB_GRADE
WHERE STUDENT_NO = 'A112113' ;

SELECT SUBSTR(TERM_NO,1,4) AS 년도,
       ROUND(AVG(POINT),1) AS "년도 별 평점"
FROM TB_GRADE
WHERE STUDENT_NO = 'A112113'
GROUP BY SUBSTR(TERM_NO,1,4) 
ORDER BY 1; 

-- 13번
SELECT DEPARTMENT_NO AS 학과코드명,
       SUM(DECODE(ABSENCE_YN,'Y',1,0)) AS "휴학생 수"
FROM TB_STUDENT 
GROUP BY DEPARTMENT_NO
ORDER BY 1 

-- SUM(CASE WHEN ABSENCE_YN='Y' THEN 1 ELSE 0 END) AS "휴학생 수"

-- 14번
SELECT STUDENT_NAME 동일이름,
       COUNT(STUDENT_NAME) "동명인수"
FROM TB_STUDENT
GROUP BY STUDENT_NAME
HAVING COUNT(STUDENT_NAME) > 1 
ORDER BY STUDENT_NAME ;

-- 15번         
SELECT NVL(SUBSTR(TERM_NO,1,4),' ' ) AS 년도,
       NVL(SUBSTR(TERM_NO,5,2),' ') AS 학기,
       ROUND(AVG(POINT),1) AS 평점
FROM TB_GRADE
WHERE STUDENT_NO = 'A112113' 
GROUP BY ROLLUP(SUBSTR(TERM_NO,1,4),
         SUBSTR(TERM_NO,5,2))
         
-- SELECT DECODE(GROUPING(SUBSTR(TERM_NO,1,4)), 0, SUBSTR(TERM_NO,1,4),1,'') 년도

 -- 20210120 --
 --1번
SELECT STUDENT_NAME AS "학생 이름",
        STUDENT_ADDRESS AS 주소지
FROM TB_STUDENT
ORDER BY 1 ;
 
-- 2번
SELECT STUDENT_NAME,
       STUDENT_SSN
FROM TB_STUDENT
WHERE ABSENCE_YN = 'Y'
ORDER BY 2 ;

-- 3번
SELECT STUDENT_NAME 학생이름,
       STUDENT_NO 학번,
       STUDENT_ADDRESS "거주지 주소"
FROM TB_STUDENT
WHERE STUDENT_ADDRESS LIKE '강원도%' 
      OR STUDENT_ADDRESS LIKE '경기도%' 
      AND STUDENT_NO LIKE '9%'
ORDER BY 1,2,3 ; 

-- 4번
SELECT PROFESSOR_NAME,
        PROFESSOR_SSN
FROM TB_PROFESSOR 
JOIN TB_DEPARTMENT USING (DEPARTMENT_NO) 
WHERE DEPARTMENT_NO = '005' 
ORDER BY 2 ;

-- 5번
SELECT STUDENT_NO,
       POINT
FROM TB_STUDENT
JOIN TB_GRADE USING (STUDENT_NO) 
WHERE TERM_NO = '200402' AND CLASS_NO = 'C3118100'
ORDER BY 2 DESC, 1 ;

-- 6번
SELECT STUDENT_NO,
       STUDENT_NAME,
       DEPARTMENT_NAME
FROM TB_STUDENT
JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
ORDER BY 1,2,3 ;

-- 7번
SELECT CLASS_NAME,
       DEPARTMENT_NAME
FROM TB_CLASS
JOIN TB_DEPARTMENT USING (DEPARTMENT_NO) ;

-- 8번
SELECT CLASS_NAME,
       PROFESSOR_NAME
FROM TB_CLASS
JOIN TB_CLASS_PROFESSOR USING (CLASS_NO)
JOIN TB_PROFESSOR USING (PROFESSOR_NO) ;

-- 9번
-- 결과는 나옴 / 기본키와 외래키 관계인데 ON을 쓰는 이유?!
-- DEPARTMENT_NO가 여러개의 테이블에 존재하기 때문
SELECT CLASS_NAME,
       PROFESSOR_NAME
FROM TB_CLASS
JOIN TB_CLASS_PROFESSOR C USING (CLASS_NO)
JOIN TB_PROFESSOR P USING (PROFESSOR_NO)
JOIN TB_DEPARTMENT D ON (D.DEPARTMENT_NO = P.DEPARTMENT_NO)
WHERE CATEGORY = '인문사회' ;

-- 10번
-- 어메이징
SELECT STUDENT_NO 학번, 
       STUDENT_NAME "학생 이름",
       ROUND(AVG(POINT),1) "전체 평점"
FROM TB_STUDENT 
JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
JOIN TB_GRADE USING (STUDENT_NO) 
WHERE DEPARTMENT_NAME = '음악학과' 
GROUP BY STUDENT_NO, STUDENT_NAME

-- 11번
SELECT DEPARTMENT_NAME 학과이름,
       STUDENT_NAME 학생이름,
       PROFESSOR_NAME 지도교수이름
FROM TB_DEPARTMENT
JOIN TB_STUDENT USING (DEPARTMENT_NO)
JOIN TB_PROFESSOR ON (PROFESSOR_NO = COACH_PROFESSOR_NO) 
WHERE STUDENT_NO = 'A313047' ;

-- 12번
SELECT STUDENT_NAME,
       TERM_NO
FROM TB_STUDENT S
JOIN TB_GRADE USING (STUDENT_NO) 
JOIN TB_CLASS USING (CLASS_NO)
WHERE TERM_NO LIKE '2007%' AND CLASS_NAME = '인간관계론'

-- 13번
SELECT CLASS_NAME,
       DEPARTMENT_NAME
FROM TB_CLASS
JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
FULL JOIN TB_CLASS_PROFESSOR USING (CLASS_NO)
WHERE CATEGORY = '예체능' AND PROFESSOR_NO IS NULL

-- 20210121 --
-- 14번
-- NULL값이 출력되지 않을 땐 OUTER JOIN 생각하기
SELECT STUDENT_NAME 학생이름,
       CASE WHEN COACH_PROFESSOR_NO IS NULL THEN '지도교수 미지정'
       ELSE PROFESSOR_NAME
       END 지도교수
FROM TB_STUDENT
JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
FULL JOIN TB_PROFESSOR ON (PROFESSOR_NO = COACH_PROFESSOR_NO)
WHERE DEPARTMENT_NAME = '서반아어학과'
ORDER BY STUDENT_NO;

-- 15번
-- 1시간 반만에 풀었다ㅠㅠ   
SELECT  STUDENT_NO 학번,
        STUDENT_NAME 이름,
        DEPARTMENT_NAME "학과 이름",
        AVG(POINT) 평점
FROM TB_STUDENT 
JOIN TB_GRADE USING (STUDENT_NO)
JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
WHERE ABSENCE_YN = 'N' 
GROUP BY STUDENT_NO,STUDENT_NAME,DEPARTMENT_NAME
HAVING AVG(POINT)>=4.0 ;

-- 16번
SELECT CLASS_NO,
       CLASS_NAME,
       AVG(POINT)
FROM TB_CLASS
JOIN TB_GRADE USING (CLASS_NO)
JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
WHERE DEPARTMENT_NAME = '환경조경학과'
AND CLASS_TYPE = '전공선택'
GROUP BY CLASS_NO, CLASS_NAME ;

-- 17번
SELECT STUDENT_NAME,
       STUDENT_ADDRESS
FROM TB_STUDENT
JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
WHERE DEPARTMENT_NAME = ( SELECT DEPARTMENT_NAME
                            FROM TB_STUDENT
                            JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
                            WHERE STUDENT_NAME = '최경희') ;

-- 18번?!
-- 정말 모르겠다ㅠㅠ
SELECT STUDENT_NO,
       STUDENT_NAME
FROM TB_STUDENT
JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
JOIN TB_GRADE USING (STUDENT_NO)
WHERE DEPARTMENT_NAME = '국어국문학과'
AND POINT = (SELECT MAX(AVG(POINT))
                     FROM TB_GRADE
                     GROUP BY STUDENT_NO)
GROUP BY STUDENT_NO, STUDENT_NAME

-- 19번
SELECT DEPARTMENT_NAME "계열 학과명", 
      ROUND(AVG(POINT),1) 전공평점
FROM TB_DEPARTMENT
JOIN TB_CLASS USING (DEPARTMENT_NO)
JOIN TB_GRADE USING (CLASS_NO)
WHERE CATEGORY = (SELECT CATEGORY
                         FROM TB_DEPARTMENT
                         WHERE DEPARTMENT_NAME = '환경조경학과')
GROUP BY DEPARTMENT_NAME, CATEGORY





















                       










