-- 아직 입양을 못 간 동물(OUTS) 중, 가장 오래 보호소에 있었던 동물(INS) 3마리의 이름과 보호 시작일 조회
-- 보호 시작일(INS) 순 조회

SELECT I.NAME, I.DATETIME
FROM ANIMAL_INS I
LEFT JOIN ANIMAL_OUTS O
ON I.ANIMAL_ID = O.ANIMAL_ID
WHERE O.ANIMAL_ID IS NULL
ORDER BY I.DATETIME LIMIT 3;

