-- 보호소에 들어올 당시(INS)에는 중성화되지 않았지만
-- 보호소를 나갈 당시(OUTS)에는 중성화된 동물의 아이디와 종, 이름 조회
-- 아이디 순 조회

SELECT O.ANIMAL_ID, O.ANIMAL_TYPE, O.NAME
FROM ANIMAL_INS I
INNER JOIN ANIMAL_OUTS O
ON I.ANIMAL_ID = O.ANIMAL_ID
WHERE I.SEX_UPON_INTAKE LIKE 'Intact%'
AND O.SEX_UPON_OUTCOME NOT IN ('Intact Male', 'Intact Female')
ORDER BY O.ANIMAL_ID;

-- SELECT I.ANIMAL_ID, I.ANIMAL_TYPE, I.NAME
-- FROM ANIMAL_INS I
-- JOIN ANIMAL_OUTS O
-- ON I.ANIMAL_ID = O.ANIMAL_ID
-- WHERE I.SEX_UPON_INTAKE LIKE '%Intact%'
-- AND (O.SEX_UPON_OUTCOME LIKE '%Spayed%' OR O.SEX_UPON_OUTCOME LIKE '%Neutered%')
-- ORDER BY I.ANIMAL_ID ASC;
